#!/bin/sh

set -e

# 执行安装后的操作
echo "Start to install"

# 输出一些调试信息
echo "Copying tea.desktop..."
mv -f /application/lib/tea.desktop /usr/share/applications/
echo "Copying tea.png..."
mv -f /application/lib/tea.png /usr/share/pixmaps/
echo "Copying tea executable..."
mv -f /application/tea/* /usr/bin/

# 设置环境变量
echo "Set QT_PLUGIN_PATH in file .profile"
echo "QT_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/qt5/plugins" >> ~/.profile

echo "Install ok"

