#!/bin/sh

set -e

# 执行卸载后的操作
echo "Start to remove"
rm -f /usr/share/applications/tea.desktop
rm -f /usr/share/pixmaps/tea.png
rm -rf /usr/bin/tea

# 移除环境变量
echo "Remove QT_PLUGIN_PATH from file .profile"
sed -i '/QT_PLUGIN_PATH/d' ~/.profile

echo "Remove finished!"

# 如果需要重新加载某些服务或通知系统有关更改，可以在这里添加额外的命令

