name: Build and Create .deb

on:
  push:
    branches:
      - main  # 根据您的默认分支名进行调整
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Setup Qt
      uses: jurplel/install-qt-action@v2
      with:
        qt-version: '5.15'  # 使用您的 Qt 版本

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential # 或者其他您的项目需要的依赖
        
    - name: install freeglut
      run: sudo apt-get install freeglut3-dev
    
    - name: Build project
      run: qmake && make
      
    - name: Install dpkg and fakeroot
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg fakeroot

    - name: Prepare DEB package structure
      run: |
        mkdir -p deb-package/DEBIAN
        
        cat <<EOF > deb-package/DEBIAN/control
        Source: tea
        Section: devel
        Priority: optional
        Maintainer: LvHang <850609180@qq.com>
        Build-Depends: debhelper (>= 12), qt5-default, libqt5opengl5-dev
        Standards-Version: 4.5.1
        Package: tea
        Architecture: amd64
        Depends: libqt5core5a, libqt5gui5, libqt5opengl5
        Description: Just A Test
        Version:0.1
        EOF
        chmod 0755 deb-package/DEBIAN/control
        
        cat <<EOF > deb-package/DEBIAN/postinst
        set -e
        echo "Start to install"
        echo "Copying tea.desktop..."
        mv -f /application/lib/tea.desktop /usr/share/applications/
        echo "Copying tea.png..."
        mv -f /application/lib/tea.png /usr/share/pixmaps/
        echo "Copying tea executable..."
        mv -f /application/tea/* /usr/bin/
        # 设置环境变量
        echo "Set QT_PLUGIN_PATH in file .profile"
        echo "QT_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/qt5/plugins" >> ~/.profile
        echo "Install ok"
        EOF
        chmod 0755 deb-package/DEBIAN/postinst

        cat <<EOF > deb-package/DEBIAN/postrm
        set -e
        # 执行卸载后的操作
        echo "Start to remove"
        rm -f /usr/share/applications/tea.desktop
        rm -f /usr/share/pixmaps/tea.png
        rm -rf /usr/bin/tea
        # 移除环境变量
        echo "Remove QT_PLUGIN_PATH from file .profile"
        sed -i '/QT_PLUGIN_PATH/d' ~/.profile
        echo "Remove finished!"
        EOF
        chmod 0755 deb-package/DEBIAN/postrm

        mkdir -p deb-package/application
        mkdir -p deb-package/application/lib
        mkdir -p deb-package/application/tea

        cat <<EOF > deb-package/application/lib/tea.desktop
        [Desktop Entry]
        Version=0.1   #应用程序版本
        Name=tea  #应用程序名
        Comment=just a test  #应用程序描述
        Exec=/usr/bin/tea                     #可运行应用程序最终的绝对路径
        keywords=qt,opengl          #在dasn串搜索时，可用的关键字
        StartupNotify=true                        #这个不知道是什么意思
        Terminal=false                            #运行时不需要打开终端
        Type=Application                          #应用程序类型，在dash和分类中会有显示，还有其它的类型
        Categories=Utility;Application;           #应用程序的分类，工具/应用程序
        Hidden=false                              #是否隐藏（否），不知道是什么意思
        Icon=/usr/share/pixmaps/tea.png       #应用程序图标名的绝对路径
        EOF
        chmod 0755 deb-package/application/lib/tea.desktop
        
        cp tea.png deb-package/application/lib/tea.png
        cp -r tea deb-package/application/tea

    - name: Create .deb file
      run: |
        sudo dpkg -b    deb-package/      test.deb
        # 在这里执行创建 .deb 文件的命令
        # 通常是通过 dpkg-buildpackage 或者其他打包工具

    - name: Upload .deb file
      uses: actions/upload-artifact@v2
      with:
        name: deb-package
        path: test.deb  # 替换为实际的 .deb 文件路径
