name: Build and Create .deb

on:
  push:
    branches:
      - main  # 根据您的默认分支名进行调整
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Setup Qt
      uses: jurplel/install-qt-action@v2
      with:
        qt-version: '5.15'  # 使用您的 Qt 版本

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential # 或者其他您的项目需要的依赖
    - name: install freeglut
      run: sudo apt-get install freeglut3-dev
    
    - name: Build project
      run: qmake && make

    - name: Create .deb file
      run: |
        sudo dpkg -b    mydeb_1/      test.deb
        # 在这里执行创建 .deb 文件的命令
        # 通常是通过 dpkg-buildpackage 或者其他打包工具

    - name: Upload .deb file
      uses: actions/upload-artifact@v2
      with:
        name: deb-package
        path: test.deb  # 替换为实际的 .deb 文件路径
